export enum ECommandNames {
    INIT_STATE_MACHINE = "INIT_STATE_MACHINE",
    LOAD_ASSETS = "LOAD_ASSETS",
    LOAD_GAME_CONFIG = "LOAD_GAME_CONFIG",
    LOAD_SUB_CONFIGS = "LOAD_SUB_CONFIGS",
    DRAW_APP = "DRAW_APP",
}
