export enum EImageNames {
    BUTTON_START = "button_start.png",
    SMALL_WALL_1 = "small_wall_1.png",
    SMALL_WALL_2 = "small_wall_2.png",
    SMALL_WALL_3 = "small_wall_3.png",
    SMALL_WALL_4 = "small_wall_4.png",
    WALL = "wall.png",
    WATER = "water.png",
    LEAVES = "leaves.png",
    EAGLE = "eagle.png",
    TANK_ENEMY_BLUE = "enemy_blue.png",
    TANK_ENEMY_RED = "enemy_red.png",
    TANK_ENEMY_WHITE = "enemy_white.png",
    TANK = "tank.png",
    BULLET = "bullet.png",
    BULLET_ENEMY = "enemy_bullet.png",
}
