export enum EStateNames {
    PRELOADING = "PRELOADING",
    MAIN_MENU = "MAIN_MENU",
    START_SCREEN = "START_SCREEN",
    ACTIVE_GAME = "ACTIVE_GAME",
    OPTIONS_MENU = "OPTIONS_MENU",
    GAME_OVER_WIN = "GAME_OVER_WIN",
    GAME_OVER_LOSE = "GAME_OVER_LOSE",
    GAME_OVER_CONTINUE = "GAME_OVER_CONTINUE",
}
